[package]
name = "crater"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[profile.dev]
opt-level = 0

[dependencies]
base64 = "0.13.0"
bytes = "0.4.9"
bytes_1 = { version = "1", package = "bytes" }
chrono = { version = "0.4", features = ["serde"] }
crates-index = "0.18"
crossbeam-utils = "0.8"
crossbeam-channel = "0.5"
csv = "1.0.2"
docsrs-metadata = { git = "https://github.com/rust-lang/docs.rs/" }
dotenv = "0.15"
failure = "0.1.3"
flate2 = "1"
http = "0.1.10"
hyper = "0.12.8"
lazy_static = "1.0"
mime = "0.3.1"
minifier = { version = "0.0.20", features = ["html"] }
r2d2 = "0.8.2"
r2d2_sqlite = "0.21.0"
rusqlite = { version = "0.28.0", features = ["chrono", "functions", "bundled"] }
rand = "0.8"
regex = "1.0"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_regex = "0.3.0"
structopt = "0.2"
structopt-derive = "0.2"
tar = "0.4.36"
tempfile = "3.0.0"
tera = "0.11.7"
toml = "0.4.6"
url = "2"
walkdir = "2"
warp = "0.1.9"
log = "0.4.6"
env_logger = "0.9.0"
hmac = "0.12"
sha-1 = "0.10"
rust_team_data = { git = "https://github.com/rust-lang/team" }
systemstat = "0.1.11"
rustwide = { version = "0.15.0", features = ["unstable", "unstable-toolchain-ci"] }
percent-encoding = "2.1.0"
remove_dir_all = "0.7"
ctrlc = "3.1.3"
prometheus = "0.7.0"
cargo_metadata = "0.12.1"
indexmap = "1.4.0"
tokio = "1.18"
aws-types = { version = "0.46", features = ["hardcoded-credentials"] }
aws-smithy-http = "0.46"
aws-smithy-async = "0.46"
aws-sdk-s3 = "0.16"

[dev-dependencies]
assert_cmd = "2.0.4"
difference = "2.0.0"
num_cpus = "1.8.0"
predicates = "1.0.0"
