[package]
name = "faulty-deps"
version = "0.1.0"
edition = "2021"

[dependencies]
error_code = {git = "https://github.com/rust-lang/crater", rev = "c3f462bdab37a93c24b2b172b90564749e892cbc"}
lazy_static = "=0.1.0"
